#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus
yabai -m config window_zoom_persist off
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.2
yabai -m config window_shadow float

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_animation_duration 0
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config auto_padding on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config top_padding 0 \
  window_gap 4

# general space settings
yabai -m config layout bsp

# Not manage this apps
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="^Microsoft Teams*" title="^(Daily - Valencia)" manage=off
yabai -m rule --add app="^IntelliJ*" title="^(Evaluate|Settings)" manage=off

yabai -m rule --add app="^Brave Browser$" space=2
yabai -m rule --add app="^Alacritty$" space=1
yabai -m rule --add app="^Slack$" space=8
yabai -m rule --add app="^Microsoft Teams*" space=9
yabai -m rule --add app="^IntelliJ*" space=3
yabai -m rule --add app="^Spotify$" space=10

# spacebar padding on top screen
yabai -m config external_bar all:40:0

echo "yabai configuration loaded.."
