#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"

# global settings
yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist off \
  window_shadow on \
  window_animation_duration 0.0 \
  window_animation_frame_rate 120 \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 1.0 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 10 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10 \
  window_gap 10 \
  layout bsp \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  external_bar all:42:0

# Not manage this apps
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="^Microsoft Teams*" title="^Daily - Valencia" manage=off
yabai -m rule --add app="^IntelliJ*" title="^(Evaluate|Settings)" manage=off
yabai -m rule --add app="^FortiClient" manage=off

yabai -m rule --add app="^(Arc|Brave Browser|Google Chrome)$" space=2
yabai -m rule --add app="^Alacritty$" space=1
yabai -m rule --add app="^Slack$" space=7
yabai -m rule --add app="^Microsoft Teams*" space=8
yabai -m rule --add app="^IntelliJ*" space=3
yabai -m rule --add app="^Spotify$" space=10
yabai -m rule --add app="^Discord$" space=9
yabai -m rule --add app="^Obsidian$" space=4

echo "yabai configuration loaded.."
