# --- Workspace assignments ---
windowrulev2 = workspace 1, class:alacritty
windowrulev2 = workspace 2, class:helium
windowrulev2 = workspace 9, class:org.telegram.desktop
windowrulev2 = workspace 9, class:brave-web.whatsapp.com__-Default
windowrulev2 = workspace 10, class:spotify

# --- JetBrains IDEs ---
windowrulev2 = float, class:^(jetbrains-.*)$, title:^(?:Project Structure|Settings|Preferences|Open File|Save As)
windowrulev2 = nofocus, class:^(jetbrains-.*)$, title:^(?:Tip of the Day)$

